<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Hub Spot Test Sanity Suite" duration-ms="33968" started-at="2019-10-12T21:17:03Z" finished-at="2019-10-12T21:17:37Z">
    <groups>
    </groups>
    <test name="hub spot Sanity Test" duration-ms="33968" started-at="2019-10-12T21:17:03Z" finished-at="2019-10-12T21:17:37Z">
      <class name="com.hubspot.tests.LoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.hubspot.tests.LoginTest@6e4de19b]" name="setUp" is-config="true" duration-ms="7813" started-at="2019-10-12T21:17:03Z" finished-at="2019-10-12T21:17:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginTest()[pri:1, instance:com.hubspot.tests.LoginTest@6e4de19b]" name="loginTest" duration-ms="4627" started-at="2019-10-12T21:17:11Z" description="login test with correct username and correct password" finished-at="2019-10-12T21:17:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.hubspot.tests.LoginTest@6e4de19b]" name="tearDown" is-config="true" duration-ms="96" started-at="2019-10-12T21:17:15Z" finished-at="2019-10-12T21:17:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.hubspot.tests.LoginTest@6e4de19b]" name="setUp" is-config="true" duration-ms="6518" started-at="2019-10-12T21:17:15Z" finished-at="2019-10-12T21:17:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginTest1()[pri:2, instance:com.hubspot.tests.LoginTest@6e4de19b]" name="loginTest1" duration-ms="517" started-at="2019-10-12T21:17:22Z" description="login test with incorrect username and incorrect password" finished-at="2019-10-12T21:17:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest1 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.hubspot.tests.LoginTest@6e4de19b]" name="tearDown" is-config="true" duration-ms="87" started-at="2019-10-12T21:17:23Z" finished-at="2019-10-12T21:17:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.hubspot.tests.LoginTest@6e4de19b]" name="setUp" is-config="true" duration-ms="6692" started-at="2019-10-12T21:17:23Z" finished-at="2019-10-12T21:17:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginTest2()[pri:3, instance:com.hubspot.tests.LoginTest@6e4de19b]" name="loginTest2" duration-ms="519" started-at="2019-10-12T21:17:29Z" description="login test with correct username and incorrect password" finished-at="2019-10-12T21:17:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest2 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.hubspot.tests.LoginTest@6e4de19b]" name="tearDown" is-config="true" duration-ms="84" started-at="2019-10-12T21:17:30Z" finished-at="2019-10-12T21:17:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.hubspot.tests.LoginTest@6e4de19b]" name="setUp" is-config="true" duration-ms="6702" started-at="2019-10-12T21:17:30Z" finished-at="2019-10-12T21:17:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginPageTitleTest()[pri:4, instance:com.hubspot.tests.LoginTest@6e4de19b]" name="loginPageTitleTest" duration-ms="16" started-at="2019-10-12T21:17:37Z" description="login page title test... " finished-at="2019-10-12T21:17:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[HubSpot Login expected:<HubSpot Login> but was:<title is in correct...>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: HubSpot Login expected:<HubSpot Login> but was:<title is in correct...>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
at com.hubspot.tests.LoginTest.loginPageTitleTest(LoginTest.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.hubspot.tests.LoginTest@6e4de19b]" name="tearDown" is-config="true" duration-ms="86" started-at="2019-10-12T21:17:37Z" finished-at="2019-10-12T21:17:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.hubspot.tests.LoginTest -->
    </test> <!-- hub spot Sanity Test -->
  </suite> <!-- Hub Spot Test Sanity Suite -->
</testng-results>
